# folder: docs/ # The folder that required to be parsed
httpsOnly: true # If you want enforce only HTTPS links
pullRequestReview: true # If you want a nice review in your pull requests
ignore: 
  urls: # Array of url to ignore, wildcarded
  files: # Array of markdown file the action shouldn't parse.  Addressed by relative path from the folder shared above
delay:
  # 'https://gitlab.com': 500 # Perform a pause of 500ms at each call matching the url
