name: Markdown lint
# https://github.com/marketplace/actions/404-links
on:
  push:
    branches: [ master ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'restqa-404-links'
      uses: restqa/404-links@3.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
